<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ApplicationIcon>Assets\Airly.ico</ApplicationIcon>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AirlyClient</AssemblyName>
    <RootNamespace>AirlyClient</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
</Project>
